%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\08_PhD\04_CASE_STUDIES\Piave\DATA\SURVEYS\DATA_ANALYSIS\Summary_Table_Modified.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 20-07-2025 09:53:33

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 17);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A3:Q42";

% Specify column names and types
opts.VariableNames = ["Location", "Lithology", "Origin", "Distance", "SampleSize", "b", "b_StDev", "elongation", "elongation_StDev", "Area", "Area_StDev", "Roundness", "Roundness_StDev", "Circularity", "Circularity_StDev", "NormCirc", "NormCirc_StDev"];
opts.VariableTypes = ["double", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Lithology", "Origin"], "EmptyFieldRule", "auto");

% Import the data
T_Summary = readtable("Summary_Table.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts