function Paths = ImportPaths(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  W100PATHS1 = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the numeric
%  data.
%
%  W100PATHS1 = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  W100PATHS1 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  W100PATHS = importfile("D:\08_PhD\04_CASE_STUDIES\Piave\DATA\SURVEYS\DATA_ANALYSIS\W100_PATHS.xlsx", "Sheet1", [2, 25]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Sep-2023 16:48:49

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 25];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 24);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":X" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Loc_1", "Loc_2", "Loc_3", "Loc_4", "Loc_5", "Loc_6", "Loc_7", "Loc_8", "Loc_9", "Loc_10", "Loc_11", "Loc_12", "Loc_13", "Loc_14", "Loc_15", "Loc_16", "Loc_17", "Loc_18", "Loc_19", "Loc_20", "Loc_21", "Loc_22", "Loc_23", "Loc_24"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
Paths = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":X" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Paths = [Paths; tb]; %#ok<AGROW>
end

%% Convert to output type
Paths = table2array(Paths);
end