%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\08_PhD\04_CASE_STUDIES\Piave\DATA\SURVEYS\DATA_ANALYSIS\INPUTS\Locations_Renaming.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 06-07-2025 05:57:35

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:B25";

% Specify column names and types
opts.VariableNames = ["LocationOld", "LocationNew"];
opts.VariableTypes = ["double", "double"];

% Import the data
LocationsRenaming = readtable("D:\08_PhD\04_CASE_STUDIES\Piave\DATA\SURVEYS\DATA_ANALYSIS\INPUTS\Locations_Renaming.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts