%--------------------------------------------------------------------------
%                           IMPORT DATA
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
OptParamAVG = importfile("Opt_Param_AVG.xlsx", "Sheet1", [2, Inf]);

load('Arenites_Validation_Inputs.mat');

% addpath 'D:\02_DATA\CODES\MATLAB Codes\EXPORT_FIG'
% addpath 'C:\Program Files\gs\gs10.05.1'
% addpath 'D:\08_PhD\04_CASE_STUDIES\Piave\DATA\SURVEYS\DATA_ANALYSIS\REQUIRED_FUNCTIONS';
addpath(genpath('..'))
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\08_PhD\04_CASE_STUDIES\Piave\DATA\SURVEYS\DATA_ANALYSIS\RESULTS\ARENITES_VALIDATION\Point_Sources.xlsx
%    Worksheet: Sources_Topology
%
% Auto-generated by MATLAB on 13-07-2025 02:19:48

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Sources_Topology";
opts.DataRange = "A2:D17";

% Specify column names and types
opts.VariableNames = ["Source", "Source_x", "Confluence", "Counfluence_x"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Import the data
Sources = readtable("Point_Sources.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% DEFINITION MODEL PARAMETERS
i=1;                                        % i=1 for ARENITES; i=2 for METABASALTS
Lithologies=OptParamAVG.Lithology(i);
C0=OptParamAVG.C0(i);
a=OptParamAVG.a(i);
ka=OptParamAVG.ka(i);
%--------------------------------------------------------------------------
C_max=1;
mu_max=1;
lambda=450;                                 %exponential coefficient, in [m]
%--------------------------------------------------------------------------
Sources=round(Sources);
RiverLength=max(Sources.Source_x);
NumSources=size(Sources,1);
L_ActiveSources=NaN(NumSources,RiverLength);
P_L=zeros(NumSources,RiverLength);
C_Mod_Sources=zeros(NumSources,RiverLength);
for x=RiverLength:-1:1
    NumUpStreamSources(x)=sum(Sources.Counfluence_x>=x);%NumUpStreamSources
    NumActiveSources(x)=sum(Sources.Source_x>=x);
    L_UpStreamSources(1:NumUpStreamSources(x),x)=Sources.Source_x(1:NumUpStreamSources(x))-x;
    L_ActiveSources(1:NumActiveSources(x),x)=Sources.Source_x(1:NumActiveSources(x))-x;
end
C_Mod_Sources=C_of_L_matrix(L_ActiveSources./1000,mu_max,C0,C_max,a,ka);

River_Locations=sort(unique(T.Location(T.Lithology==Lithologies&T.Origin=="RIVER")),'ascend');
River_Locations_Distances=sort(unique(T.Distance(ismember(T.Location,River_Locations))),'descend');
%--------------------------------------------------------------------------
%                   OPTIMIZATION OF LAMBDA
lambda_range=[50:1:5000];
for i=1:length(lambda_range)

    for j= 1:RiverLength

        for k=1: NumUpStreamSources(j)
            P_L(k,j)=1./lambda_range(i).*exp(-L_UpStreamSources(k,j)./lambda_range(i));
        end

        C_plot(i,j)=sum(C_Mod_Sources(1:NumUpStreamSources(j),j).*P_L(1:NumUpStreamSources(j),j))/sum(P_L(1:NumUpStreamSources(j),j));

    end
    %--------------------------------------------------------------------------
    %                   ERROR METRIC CALCULATION
    for j=1:length(River_Locations)

        % if River_Locations(j)~=21
            River_Data_AVG(j)=mean(T.NormCirc(T.Lithology==Lithologies&T.Location==River_Locations(j)&T.Origin=="RIVER"));
            Sampling_Location_Dist_Round=round(River_Locations_Distances(j));
            Model_Data(j)=C_plot(i,Sampling_Location_Dist_Round);
            Error(j)=River_Data_AVG(j)-Model_Data(j);
        % end

    end

    RMSE_Lambda(i,1)=sqrt(mean(Error.^2));
end

[min_RMSE_Lambda,I_Lambda]=min(RMSE_Lambda,[],'all','linear');
% Convert linear indices I(m) into row,col indices basedon the
% dimensions of the matrix R2
[I1_Lambda,I2_Lambda]=ind2sub([size(RMSE_Lambda,1) size(RMSE_Lambda,2)],I_Lambda);

Opt_Lambda=lambda_range(1,I1_Lambda);
Opt_C_plot(1,:)=C_plot(I1_Lambda,:);
%--------------------------------------------------------------------------
%                   PLOT LAMBDA OPTIMIZATION RESULTS
fig_lambda=figure; hold on
set(fig_lambda,'DefaultFigureColor',[1 1 1])         %Figure background color
%--------------------------------------------------------------------------
%                   DIMENSIONS
set(0,'Units','centimeters')
left=0;                         %in cm
bottom=0;                       %in cm
width=8.89;                     %in cm 8.89 for IEEE journals
hw_ratio = 0.65;                % feel free to play with this ratio
height=4;                       %in cm

positionVect = [left bottom width height];  %Size and position of figure

set(fig_lambda, 'PaperPosition', [positionVect]) %Set paper total dimension
set(gcf,'Color','white')
FontSize = 17;
set(findall(fig_lambda,'-property','FontSize'),'FontSize',FontSize) % adjust fontsize to your document
fontname = 'Times New Roman';                         %'Helvetica'
set(0, 'DefaultAxesFontName', fontname);     
set(0, 'DefaultTextFontName', fontname);    
set(0,'defaulttextinterpreter','latex')     %Allows us to use LaTeX maths notation
pl_RMSE_Lambda=plot(lambda_range,RMSE_Lambda,'DisplayName',sprintf('RMSE'),'HandleVisibility','off');
sc_RMSE_Lambda=scatter(Opt_Lambda,min_RMSE_Lambda,20,"red",'filled','DisplayName',sprintf('Optimum %s = %.0f m','\lambda ',Opt_Lambda),'HandleVisibility','on');
hold off
xlabel('$\lambda$ [m]',  'FontWeight', 'bold')
ylabel({'$RMSE$ [-]'},  'FontWeight', 'bold') % Note cell matrices for line breaks
legend('location','southeast')
legend boxoff
%--------------------------------------------------------------------------
%                   SAVE LAMBDA MINIMIZATION IMAGE
fileformat='.PDF';%'.eps' '.PDF', '.png'
%--------------------------------------------------------------------------
fileName = ['Arenites_Validation_Optimization_', datestr(now,'mmmm dd yyyy hhMM'), fileformat]; %Descriptive name timestamp and .png file format

export_fig (fileName, '-nocrop')%'-m3',

savefig(fig_lambda,['Arenites_Validation_Optimization_', datestr(now,'mmmm dd yyyy hhMM'), '.fig']);
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
% FUNCTION TO COMPUTE C of L FOR A MATRIX
function C=C_of_L_matrix(L,mu_max,C0,C_max,a,Ka)
mu=mu_max-exp(-Ka.*L);
C=C0+(C_max-C0).*(1-(1-mu./mu_max).^a).^(1/a);
for i=1:size(C,1)
    for j=1:size(C,2)
        if C(i,j)<C0
            C(i,j)=NaN;
        end
    end
end
end

%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%                   PLOTTING RESULTS
fig_1=figure;
ax_1=gca;
hold on
set(fig_1,'DefaultFigureColor',[1 1 1])         %Figure background color
set(gcf,'Color','white')
%--------------------------------------------------------------------------
%                   DIMENSIONS
set(fig_1,'Units','centimeters')
left=0;                         %in cm
bottom=0;                       %in cm
width=16.00;                    %in cm 8.89 for IEEE journals
hw_ratio = 0.65;                % feel free to play with this ratio
height=6.0;                     %in cm

positionVect = [left bottom width height];  %Size and position of figure

set(fig_1, 'PaperPosition', [positionVect]) %Set paper total dimension
% set(fig_1, 'Position', [positionVect]) %Set paper total dimension
set(gcf,'Color','white')
FontSize = 17;
set(findall(fig_1,'-property','FontSize'),'FontSize',FontSize) % adjust fontsize to your document
fontname = 'times';                         %'Helvetica'
set(0, 'DefaultAxesFontName', fontname);     
set(0, 'DefaultTextFontName', fontname);    
set(0,'defaulttextinterpreter','latex')     %Allows us to use LaTeX maths notation
%--------------------------------------------------------------------------
x_plot=1:RiverLength;
for j=1:length(Sources.Source_x)
    pl_source_traj{j}=plot(x_plot,C_Mod_Sources(j,:), 'LineStyle','--','Color','b','DisplayName',sprintf('Sources Trajectory'),'HandleVisibility','off');
end
set(pl_source_traj{1},'HandleVisibility','on')
pl_Model_traj=plot(x_plot,Opt_C_plot,'LineStyle','-','LineWidth',2,'Color','r','DisplayName',sprintf('Model results'),'HandleVisibility','on');%, '-','r'
set(gca, 'XDir','reverse')

River_Locations=sort(unique(T.Location(T.Lithology==Lithologies&T.Origin=="RIVER")),'ascend');
River_Locations_Distances=sort(unique(T.Distance(ismember(T.Location,River_Locations))),'descend');
for j=1:length(River_Locations)
    River_Data_AVG(j)=mean(T.NormCirc(T.Lithology==Lithologies&T.Location==River_Locations(j)&T.Origin=="RIVER"));
    River_Data_STD(j)=std(T.NormCirc(T.Lithology==Lithologies&T.Location==River_Locations(j)&T.Origin=="RIVER"));
    River_Data_SSize(j)=length(T.NormCirc(T.Lithology==Lithologies&T.Location==River_Locations(j)&T.Origin=="RIVER"));
    River_Data_StERR(j)=River_Data_STD(j)/sqrt(River_Data_SSize(j));
end


ColorRiver=[192, 57, 43]./255;

error_Data{i}=errorbar(gca,River_Locations_Distances,River_Data_AVG,River_Data_StERR,'vertical',"o","LineStyle","none","Color",ColorRiver, "MarkerEdgeColor",ColorRiver,"MarkerFaceColor",ColorRiver,'DisplayName',sprintf('River measurements'),'HandleVisibility','on');
%--------------------------------------------------------------------------

Creek_Locations=sort(unique(T.Location(T.Lithology==Lithologies&T.Origin=="CREEK")),'ascend');
for j=1:length(Creek_Locations)
    Creek_Data_AVG(j)=mean(T.NormCirc(T.Lithology==Lithologies&T.Location==Creek_Locations(j)&T.Origin=="CREEK"&T.Location~=16&T.Location~=12));
    Creek_Data_STD(j)=std(T.NormCirc(T.Lithology==Lithologies&T.Location==Creek_Locations(j)&T.Origin=="CREEK"&T.Location~=16&T.Location~=12));
    Creek_Data_SSize(j)=length(T.NormCirc(T.Lithology==Lithologies&T.Location==Creek_Locations(j)&T.Origin=="CREEK"&T.Location~=16&T.Location~=12));
    Creek_Data_StERR(j)=Creek_Data_STD(j)/sqrt(Creek_Data_SSize(j));
end
Creek_Locations_Distances=sort(unique(T.Distance(ismember(T.Location,Creek_Locations))),'descend');

ColorcREEK=[49, 203, 59]./255;% [172, 57, 43]

error_Data{i}=errorbar(gca,Creek_Locations_Distances,Creek_Data_AVG,Creek_Data_StERR,'vertical',"o","LineStyle","none","Color",ColorcREEK, "MarkerEdgeColor",ColorcREEK,"MarkerFaceColor",ColorcREEK,'DisplayName',sprintf('Creek measurements'),'HandleVisibility','on');
%--------------------------------------------------------------------------

Source_Locations=sort(unique(T.Location(T.Lithology==Lithologies&T.Origin=="SOURCE")),'ascend');
for j=1:length(Source_Locations)
    Source_Data_AVG(j)=mean(T.NormCirc(T.Lithology==Lithologies&T.Location==Source_Locations(j)&T.Origin=="SOURCE"));
    Source_Data_STD(j)=std(T.NormCirc(T.Lithology==Lithologies&T.Location==Source_Locations(j)&T.Origin=="SOURCE"));
    Source_Data_SSize(j)=length(T.NormCirc(T.Lithology==Lithologies&T.Location==Source_Locations(j)&T.Origin=="SOURCE"));
    Source_Data_StERR(j)=Source_Data_STD(j)/sqrt(Source_Data_SSize(j));
end
Source_Locations_Distances=sort(unique(T.Distance(ismember(T.Location,Source_Locations))),'descend');

ColorSource=[152, 57, 43]./255;

error_Data{i}=errorbar(gca,Source_Locations_Distances,Source_Data_AVG,Source_Data_StERR,'vertical',"o","LineStyle","none","Color",ColorSource, "MarkerEdgeColor",ColorSource,"MarkerFaceColor",ColorSource,'DisplayName',sprintf('Source measurements'),'HandleVisibility','on');
%--------------------------------------------------------------------------
%                   FONT SIZE
FontSize = 17;
set(findall(fig_1,'-property','FontSize'),'FontSize',FontSize) % adjust fontsize to your document
fontname = 'times';                         %'Helvetica'
set(0, 'DefaultAxesFontName', fontname);     
set(0, 'DefaultTextFontName', fontname);    
set(0,'defaulttextinterpreter','latex')     %Allows us to use LaTeX maths notation
xlabel('Distance from outlet [m]',  'FontWeight', 'bold')
ylabel({'$IR_{n}$ [-]'},  'FontWeight', 'bold') % Note cell matrices for line breaks
legend('location','northwest')
legend boxoff
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------

%--------------------------------------------------------------------------
%                   SAVE GRAPH TO FILE
%Now ready for export
% print(hfig,fname,'-dpng','-painters')
% fileformat='.PDF';%'.eps' '.PDF', '.png'
%--------------------------------------------------------------------------
fileName = ['Arenites_Validation_Confluence_', datestr(now,'mmmm dd yyyy hhMM'), fileformat]; %Descriptive name timestamp and .png file format

export_fig (fileName, '-nocrop')%'-m3',

savefig(fig_1,['Arenites_Validation_Confluence_', datestr(now,'mmmm dd yyyy hhMM'), '.fig']);
%--------------------------------------------------------------------------
dataName=['Arenites_Validation_Confluence_Results_',datestr(now,'mmmm dd yyyy hhMM'),'.mat'];
save(dataName)



%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
function OptParamAVG = importfile(workbookFile, sheetName, dataLines)
%% Input handling

% If no sheet is specified, read from Sheet1
if nargin == 1 || isempty(sheetName)
    sheetName = "Sheet1";
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Lithology", "C0", "a", "ka"];
opts.VariableTypes = ["string", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Lithology", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Lithology", "EmptyFieldRule", "auto");

% Import the data
OptParamAVG = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    OptParamAVG = [OptParamAVG; tb]; %#ok<AGROW>
end

end