%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\08_PhD\04_CASE_STUDIES\Piave\DATA\SURVEYS\DATA_ANALYSIS\RESULTS\C0_a_PLOT\C0_a_common_Ka.xlsx
%    Worksheet: OVERVIEW
%
% Auto-generated by MATLAB on 04-07-2025 03:59:49

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = "OVERVIEW";
opts.DataRange = "A2:F23";%F39

% Specify column names and types
opts.VariableNames = ["Lithology", "Quantile", "C0", "a", "Ka", "RMSE"];
opts.VariableTypes = ["categorical", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Lithology", "EmptyFieldRule", "auto");

% Import the data
OverviewTable = readtable("C0_a_common_Ka.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts
%--------------------------------------------------------------------------
% addpath 'D:\02_DATA\CODES\MATLAB Codes\EXPORT_FIG'
% addpath 'C:\Program Files\gs\gs10.05.1'
addpath(genpath('..'))
%--------------------------------------------------------------------------
fig_1=figure;
ax_1=gca;
hold on
set(fig_1,'DefaultFigureColor',[1 1 1])         %Figure background color
set(gcf,'Color','white')
%--------------------------------------------------------------------------
%                   DIMENSIONS
set(0,'Units','centimeters')
left=0;                         %in cm
bottom=0;                       %in cm
width=8.89;                     %in cm 8.89 for IEEE journals
hw_ratio = 0.65;                % feel free to play with this ratio
height=4;                       %in cm

positionVect = [left bottom width height];  %Size and position of figure

set(fig_1, 'PaperPosition', [positionVect]) %Set paper total dimension

%--------------------------------------------------------------------------
%                   FONT NAME
% listfonts
fontname = 'times';                         %'Helvetica'
set(0, 'DefaultAxesFontName', fontname);     
set(0, 'DefaultTextFontName', fontname);    
set(0,'defaulttextinterpreter','latex')     %Allows us to use LaTeX maths notation


set(findall(fig_1,'-property','Box'),'Box','off') % optional
set(findall(fig_1,'-property','Interpreter'),'Interpreter','latex') 
set(findall(fig_1,'-property','TickLabelInterpreter'),'TickLabelInterpreter','latex')

%--------------------------------------------------------------------------
%                   FONT SIZE
FontSize = 17;
set(findall(fig_1,'-property','FontSize'),'FontSize',FontSize) % adjust fontsize to your document
% set(0,'DefaultAxesFontSize',FontSize); %Eight point Times is suitable typeface for an IEEE paper. Same as figure caption size
%--------------------------------------------------------------------------
%                   LINE WIDTH
linewidth=1.5;
%--------------------------------------------------------------------------
%                   COLOR PALETTE
PS.DRed1 = [205, 97, 85]./255;
PS.DRed2 = [192, 57, 43]./255;
PS.DRed3 = [169, 50, 38]./255;
PS.DRed4 = [146, 43, 33]./255;
PS.DRed5 = [123, 36, 28]./255;

PS.DGreen1 = [69, 179, 157]./255;
PS.DGreen2 = [19, 141, 117]./255;
PS.DGreen3 = [17, 122, 101]./255;
PS.DGreen4 = [14, 102, 85]./255;
PS.DGreen5 = [11, 83, 69]./255;

PS.Green1 = [82, 190, 128]./255;
PS.Green2 = [39, 174, 96]./255;
PS.Green3 = [34, 153, 84]./255;
PS.Green4 = [30, 132, 73]./255;
PS.Green5 = [20, 90, 50]./255;

PS.Orange1 = [245, 176, 65]./255;
PS.Orange2 = [243, 156, 18]./255;
PS.Orange3 = [214, 137, 16]./255;
PS.Orange4 = [185, 119, 14]./255;
PS.Orange5 = [156, 100, 12]./255;

PS.Blue1 = [133, 193, 233]./255;
PS.Blue2 = [93, 173, 226]./255;
PS.Blue3 = [52, 152, 219]./255;
PS.Blue4 = [40, 116, 166]./255;
PS.Blue5 = [27, 79, 114]./255;
ColorPalette=PS;
%--------------------------------------------------------------------------
%                   ACTUAL PLOTTING STARTS HERE
MetabasaltsColor = PS.DGreen2;
ArenitesColor =PS.DRed2;
MarkerSize = 30;
%--------------------------------------------------------------------------
C0_plot_arenites=OverviewTable.C0(OverviewTable.Lithology=="ARENITES");
a_plot_arenites=OverviewTable.a(OverviewTable.Lithology=="ARENITES");
C0_plot_metabasalts=OverviewTable.C0(OverviewTable.Lithology=="METABASALTS");
a_plot_metabasalts=OverviewTable.a(OverviewTable.Lithology=="METABASALTS");
%--------------------------------------------------------------------------

Scatter_Aren=scatter(C0_plot_arenites,a_plot_arenites,'filled');
Scatter_Meta=scatter(C0_plot_metabasalts,a_plot_metabasalts,'filled');

set(Scatter_Aren,'SizeData',MarkerSize,'MarkerEdgeColor', ArenitesColor, 'MarkerFaceColor',ArenitesColor,'DisplayName','Arenites');%,'color',LocationColor,'filled'
set(Scatter_Meta,'SizeData',MarkerSize,'MarkerEdgeColor', MetabasaltsColor, 'MarkerFaceColor',MetabasaltsColor,'DisplayName','Metabasalts');%,'color',LocationColor,'filled'

%--------------------------------------------------------------------------
%   !!! BEFORE CONTINUING RUN CURVE FITTER TO FIT THE DATA WITH AN EXPONENTIAL
%CURVE  !!!
% At the first round:
% 1) Pause the code here. 
% 2) Open the Curve Fitter App and load the data relative to one lithology
% 3) Fit an exponential curve
% 4) Save three files: - fittedmodel_...lithology
%                      - goodness_......lithology
%                      - output_........lithology
% 5) use the following command save
% 6) at the second round, comment the command save and uncomment the
% command load.
% save("C0_a_Curve_Fitter_Results_2.mat","fittedmodel_Arenites","fittedmodel_Metabasalts","goodness_Arenites","goodness_Metabasalts","output_Arenites","output_Metabasalts")
load("C0_a_Curve_Fitter_Results_2.mat")
%--------------------------------------------------------------------------
% [fittedmodel_Metabasalts, goodness_Metabasalts]= createFit(C0_plot_metabasalts, a_plot_metabasalts)
% [fittedmodel_Arenites, goodness_Arenites]= createFit(C0_plot_arenites, a_plot_arenites)
% createFit_C0_a_Metabasalts
% createFit_C0_a_Arenites
%--------------------------------------------------------------------------
n_data_plot=100;
C0_Aren_plot=linspace(min(C0_plot_arenites),max(C0_plot_arenites),n_data_plot);
a_Aren_Plot=fittedmodel_Arenites.a*exp(fittedmodel_Arenites.b.*C0_Aren_plot);

C0_Meta_plot=linspace(min(C0_plot_metabasalts),max(C0_plot_metabasalts),n_data_plot);
a_Meta_Plot=fittedmodel_Metabasalts.a*exp(fittedmodel_Metabasalts.b.*C0_Meta_plot);

Plot_Aren=plot(C0_Aren_plot,a_Aren_Plot);
Plot_Meta=plot(C0_Meta_plot,a_Meta_Plot);

set(Plot_Aren, 'LineStyle', '--','LineWidth',linewidth,'color',ArenitesColor,'Marker', 'none','DisplayName','Arenites','HandleVisibility','off');
set(Plot_Meta, 'LineStyle', '--','LineWidth',linewidth,'color',MetabasaltsColor,'Marker', 'none','DisplayName','Metabasalts','HandleVisibility','off');

xlabel({'$C_{0}$ [-]'},  'FontWeight', 'bold') % Note cell matrices for line breaks
ylabel('a [-]',  'FontWeight', 'bold')

% str={[sprintf('$%0.4f e^{%0.4f C_{0}}$',fittedmodel_Arenites.a,fittedmodel_Arenites.b)];[sprintf('$R^{2} = %.f$',goodness_Arenites.rsquare)]};
textHandle_Aren=text(0.88,4,{[sprintf('$a= %0.4f e^{%0.4f C_{0}}$',fittedmodel_Arenites.a,fittedmodel_Arenites.b)];[sprintf('$R^{2} = %.4f$',goodness_Arenites.rsquare)]});    %sprintfc(' %d',1:numel(tenFootHorizontal))
set(textHandle_Aren,'FontSize',11,'Color',ArenitesColor);
% delete(textHandle_Aren);

textHandle_Meta=text(0.73,8,{[sprintf('$a= %0.4f e^{%0.4f C_{0}}$',fittedmodel_Metabasalts.a,fittedmodel_Metabasalts.b)];[sprintf('$R^{2} = %.4f$',goodness_Metabasalts.rsquare)]});    %sprintfc(' %d',1:numel(tenFootHorizontal))
set(textHandle_Meta,'FontSize',11,'Color',MetabasaltsColor);
% delete(textHandle_Meta);

grid on

lgd=legend('FontSize',11,'Location','northwest');
legend('boxoff')

set(gcf,'Color','white')
%--------------------------------------------------------------------------
%                   SAVING fig_1 AS PDF, PNG AND AS .fig
fileformat='.png';%'.eps' '.PDF'
filename = sprintf('C0_a_Plot_Paper_%s%s ', datestr(now,'mmmm dd yyyy hhMM'), fileformat); %['C0_a_Plot_Paper ', datestr(now,'mmmm dd yyyy hhMM'), fileformat] %Descriptive name timestamp and .png file format
export_fig (filename, '-nocrop')%'-m3',

fileformat='.PDF';%'.eps' '.PDF', '.png' '.PDF'
fileName = sprintf('C0_a_Plot_Paper_%s%s',datestr(now,'mmmm dd yyyy hhMM'),fileformat); %Descriptive name timestamp and .png file format
export_fig (fileName, '-nocrop')%'-m3',

savefig(fig_1,sprintf('C0_a_Plot_Paper_%s%s', datestr(now,'mmmm dd yyyy hhMM'), '.fig'));

%--------------------------------------------------------------------------
save("C0_a_Plot.mat")